# -*- coding: utf-8 -*-
"""magnetorquers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N38k9i0z2pSoK6dW5vTi_TXkY5VobADl

##User inputs
"""

N     = 50                        # turns
p     = 1.68E-08                  # resistivity of copper
V_s   = 3.3                       # supply voltage
A_s   = 5.80E-03                  # average surface area
A_cw  = 5.40E-09                  # cross sectional area of wire
B     = 2.50E-05                  # Earth's Mag-field
L_w   = 11.5                      # wire length

L_w

"""##Magnetorquer model"""

def torque_coil(N, p, V_s, A_s, A_cw, B, L_w):
  R = p*L_w/A_cw 
  I = V_s/R
  T = N*I*A_s*B
  return T

def series(N, p, V_s, A_s, A_cw, B, L_w):
  R = p*L_w/A_cw 
  R_tot = R*4
  I = 

def parallel():

torque = torque_coil(N, p, V_s, A_s, A_cw, B, L_w);
print(torque)